Repository MonkeyModdingTroop/MonkeyLoader, pull requests merged in 2024-07, with the labels that each got.

#24 Add OnEnabled and OnDisabled hooks to MonkeyBase
  MonkeyLoader/Configuration/ConfigKey.cs
  MonkeyLoader/Configuration/ConfigSection.cs
  MonkeyLoader/MonkeyLoader.csproj
  MonkeyLoader/Patching/MonkeyBase.cs
Labels: enhancement

#25 Make Configs IIdentifiables and move FullId to IIdentifiable
  MonkeyLoader/Configuration/Config.cs
  MonkeyLoader/Configuration/ConfigKey.cs
  MonkeyLoader/Configuration/ConfigSection.cs
  MonkeyLoader/Configuration/IConfigOwner.cs
  MonkeyLoader/IdentifiableExtensions.cs
  MonkeyLoader/Meta/IIdentifiables.cs
  MonkeyLoader/Meta/Mod.cs
  MonkeyLoader/Meta/NestedIdentifiableSearch.cs
  MonkeyLoader/MonkeyLoader.cs
  MonkeyLoader/MonkeyLoader.csproj
Labels: enhancement

#28 Add more checks to AddMod, ShutdownMod(s) and RunMod(s)
  MonkeyLoader/Meta/Mod.cs
  MonkeyLoader/MonkeyLoader.cs
Labels: bug

#30 Allow the EnumerableInjector to allow entirely new items
  MonkeyLoader/Utility/EnumerableInjector.cs
Labels: enhancement

#32 Remove text auto from .sh files
  .gitattributes
Labels: bug

#33 Adds an ItemChanged event to ConfigSections and fixes its FullId
  MonkeyLoader/Configuration/Config.cs
  MonkeyLoader/Configuration/ConfigSection.cs
  MonkeyLoader/Configuration/DefiningConfigKey.cs
Labels: bug, enhancement
